# Site settings
title: Great New Blog Title
author:
  name: Sanjith Guttikonda
  email: sanjithbusiness2013@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
theme: jekyll-theme-minimal
